# Generated by Django 5.0.4 on 2024-04-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_remove_choice_choice_date_remove_choice_user_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
            preserve_default=False,
        ),
    ]
