# Generated by Django 5.0.4 on 2024-04-14 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_choice_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='default',
        ),
        migrations.AddField(
            model_name='question',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='Default Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Edward', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Shin', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='entries.question'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='entries.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='EntryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_text', to='entries.entry')),
            ],
        ),
    ]
